### ISSUE TITLE
Pushed changes are not automatically recognized in GlotPress

### ISSUE THREAD

**Issue by KittMedia** [wearerequired/traduttore#137]
**Issue Overview**
I don’t know if it’s a bug or if I don’t understand correctly. The documentation says:
> Now, every time you push changes to GitHub, Traduttore will get notified and then attempts to update the project's translatable strings automatically.

Even if I’m using GitLab, I think this would work exactly similar? So the web hook works and I receive a 200 status code but new strings are not visible in GlotPress unless I manually use `wp traduttore project update <id>`.

Am I doing something wrong or is this not intended to work with GitLab?

A sample project information:

```
Project ID:		6
Project name:		Test-Projekt
Project slug:		test-private
Version:		1.0.0
Text domain:		rh-test
Last updated:		2018-12-04 10:45:04
Repository Cache:	/tmp/traduttore-git.domain.tld-matze-test-private
Repository URL:		https://git.domain.tld/matze/test-private
Repository Type:	gitlab
Repository VCS Type:	git
Repository Visibility:	public
Repository SSH URL:	git@git.domain.tld:matze/test-private.git
Repository HTTPS URL:	https://git.domain.tld/matze/test-private.git
Repository Instance:	Example_GitLab_Repository
Loader Instance:	Required\Traduttore\Loader\Git
```

**Versions**

* Browser: Safari 12.0.1
* PHP: 7.1.24
* WP-CLI: 2.0.1
* GlotPress: 2.3.1
* WordPress: 4.9.8

**Comment by swissspidy** [comment]
When Traduttore receives an incoming webhook, it responds with a status 200 and schedules a task in the background to do the update. You can verify this using the `wp cron` family of commands.

Traduttore relies on WordPress’ built-in cron functionality to schedule single events. This functionality relies on users visiting your WordPress site in order to execute scheduled events.

To make sure your events are executed on time, we suggest setting up system cron jobs that run reliably every few minutes.

[Learn more about hooking WP-Cron into the system task scheduler.](https://developer.wordpress.org/plugins/cron/hooking-into-the-system-task-scheduler/)

**Comment by KittMedia** [comment]
Thank you for your quick response!

I checked it now via `wp cron event list` and this time everything worked fine. Maybe there was something broken but now it works. Great project!
